on:
  push:
    branches: [master]
  pull_request:
    types:
      - synchronize # PR was updated
      - opened # PR was open
      - reopened # PR was closed and is now open again

concurrency:
  # Make sure we run only the latest workflow for a branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.5"
          - "3.3"
          - "3.0"
    env:
      RUBY_VERSION: $${ matrix.ruby }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run unit tests
        run: bundle exec rspec
